rule imagemagick_str2img:
    # Use convert -list font to browse available fonts.
    output: "str_image.png"
    params:
        string = "Hello world!", font = "Noto-Mono",
        width = 1000, height = 600, bg = "white", fg = "black"
    conda: "imagemagick.yaml"
    shell: """
        convert -background {params.bg} -fill {params.fg} -font {params.font} \
            -size {params.width}x{params.height} \
            label:'{params.string}' {output}"""

rule imagemagick_txt2img:
    output: "txt_image.png"
    input: "image.txt"
    params: width = 1000, height = 600, bg = "white", fg = "black"
    conda: "imagemagick.yaml"
    shell: """
        convert -background {params.bg} -fill {params.fg} \
            -page {params.width}x{params.height} \
            TEXT:{input} {output}"""

rule _example_image_txt:
    output: "image.txt"
    shell: "echo Hello World > {output}"
